# First-boot script generation for post-install configuration
# shellcheck shell=bash

firstboot_generate() {
    local working_dir="${PVE_WORKING_DIR:-/root}"
    local output_dir="${working_dir}/generated"
    local output_file="${output_dir}/first-boot.sh"

    mkdir -p "$output_dir"

    log_info "Generating first-boot script..."

    local iface="${PVE_PREDICTED_IFACE:-${PVE_INTERFACE}}"
    local dns_line=""
    for dns in $PVE_DNS_SERVERS; do
        dns_line+="nameserver ${dns}"$'\n'
    done

    # Build the interfaces file content via the active provider
    local interfaces_content
    interfaces_content="$(provider_render_interfaces)"

    # Build the hosts file content
    local hosts_content
    hosts_content="$(firstboot_render_hosts)"

    # Build the sysctl content
    local sysctl_content="net.ipv4.ip_forward=1
net.ipv6.conf.all.forwarding=1"

    # Add conntrack tuning for NAT setups (prevents exhaustion with many VMs)
    if [[ "$PVE_NETWORK_MODE" == "nat" ]]; then
        sysctl_content+="
net.netfilter.nf_conntrack_max=1048576
net.netfilter.nf_conntrack_tcp_timeout_established=28800"
    fi

    cat > "$output_file" <<'FBHEADER'
#!/bin/bash
# Proxmox VE First-Boot Configuration Script
# Generated by pve-dedicated -- do not edit manually
#
# IMPORTANT: this script intentionally does NOT use `set -e`. First-boot
# is a best-effort post-install configurator -- a transient failure in
# one optional step (e.g., apt cannot reach a mirror, a pmxcfs symlink
# clash, a kernel module already loaded) MUST NOT abort the rest of
# the script and leave the system half-configured. We keep `-u` to catch
# typos in variable names and `pipefail` to catch silent pipeline errors,
# but individual commands are expected to handle their own failures (or
# fail loudly while still letting subsequent steps run).
set -uo pipefail

LOG="/var/log/pve-first-boot.log"
exec > >(tee -a "$LOG") 2>&1
echo "[$(date)] First-boot configuration starting..."

FBHEADER

    cat >> "$output_file" <<FBNET
# --- Network Interfaces ---
cat > /etc/network/interfaces <<'INTERFACES_EOF'
${interfaces_content}
INTERFACES_EOF
echo "[$(date)] Network interfaces configured"

FBNET

    cat >> "$output_file" <<'FBNETAPPLY'
# --- Apply new network config IMMEDIATELY ---------------------------------
# The Proxmox auto-installer captured the QEMU install-time DHCP lease
# (typically 10.0.2.15 from QEMU user-mode networking) as the system's
# initial /etc/network/interfaces. We just overwrote that with the real
# provider config; without applying it now, vmbr0 keeps the QEMU IP and
# every apt call below fails because 10.0.2.x has no real path to the
# internet on bare metal. Symptom: proxmox-first-boot-multi-user.service
# dies with apt status 100 mid-script.
echo "[$(date)] Applying new network config..."
network_apply_status=0
if command -v ifreload >/dev/null 2>&1; then
    # ifupdown2 (Proxmox default) -- safe in-place reload.
    ifreload -a 2>&1 || network_apply_status=$?
elif command -v ifup >/dev/null 2>&1; then
    # Plain ifupdown -- bring stale bridges down explicitly first.
    ifdown vmbr0 2>/dev/null || true
    ifdown vmbr1 2>/dev/null || true
    ifup -a 2>&1 || network_apply_status=$?
else
    systemctl restart networking 2>&1 || network_apply_status=$?
fi
if [ "$network_apply_status" -ne 0 ]; then
    echo "[$(date)] WARN: network apply returned ${network_apply_status} (continuing)"
fi

# Wait up to 120s for the network to be ACTUALLY reachable, not just for a
# default route to be installed in the kernel routing table. A static route
# pointing at a NIC that hasn't yet linked up will be marked `linkdown` by
# the kernel; our previous "wait for default route" loop returned true
# instantly while apt then hung for 70s per call waiting on TCP timeouts.
# OVH's switch port authorisation can take 10-60s after first interface up.
echo "[$(date)] Waiting for network reachability via the new config..."
network_ok=0
i=0
while [ "$i" -lt 60 ]; do
    if ip route show default 2>/dev/null | grep -qE 'default via [0-9.]+'; then
        gw="$(ip route show default 2>/dev/null | awk '/default via/ {print $3; exit}')"
        if [ -n "$gw" ] \
           && ip link show vmbr0 2>/dev/null | grep -q 'state UP' \
           && ping -c 1 -W 2 "$gw" >/dev/null 2>&1; then
            echo "[$(date)] Network reachable after $((i * 2))s (gw ${gw} answered ping)"
            network_ok=1
            break
        fi
    fi
    sleep 2
    i=$(( i + 1 ))
done
if [ "$network_ok" -eq 0 ]; then
    echo "[$(date)] WARN: gateway not reachable after 120s; apt calls below will likely fail"
fi
ip -brief route show default 2>/dev/null || true
ip -brief addr show vmbr0 2>/dev/null || true

FBNETAPPLY

    cat >> "$output_file" <<FBHOSTS
# --- Hostname ---
echo "${PVE_HOSTNAME}" > /etc/hostname
hostnamectl set-hostname "${PVE_HOSTNAME}" 2>/dev/null || true

cat > /etc/hosts <<'HOSTS_EOF'
${hosts_content}
HOSTS_EOF
echo "[$(date)] Hostname and hosts configured"

FBHOSTS

    cat >> "$output_file" <<FBDNS
# --- DNS ---
cat > /etc/resolv.conf <<'DNS_EOF'
${dns_line}DNS_EOF
echo "[$(date)] DNS configured"

FBDNS

    cat >> "$output_file" <<FBSYSCTL
# --- Sysctl ---
cat > /etc/sysctl.d/99-proxmox.conf <<'SYSCTL_EOF'
${sysctl_content}
SYSCTL_EOF
sysctl -p /etc/sysctl.d/99-proxmox.conf >/dev/null 2>&1 || true
echo "[$(date)] Sysctl configured"

FBSYSCTL

    cat >> "$output_file" <<'FBIPV4'
# --- IPv4 Preference (Hetzner IPv6 routing can be unreliable) ---
# Make DNS resolution prefer IPv4 over IPv6 system-wide.
# This prevents timeouts when IPv6 is configured but routing is broken.
if [ -f /etc/gai.conf ]; then
    if ! grep -q '^precedence ::ffff:0:0/96  100' /etc/gai.conf; then
        echo 'precedence ::ffff:0:0/96  100' >> /etc/gai.conf
    fi
else
    echo 'precedence ::ffff:0:0/96  100' > /etc/gai.conf
fi

# Force apt to use IPv4 (persistent, survives reboots)
echo 'Acquire::ForceIPv4 "true";' > /etc/apt/apt.conf.d/99force-ipv4

echo "[$(date)] IPv4 preference configured (gai.conf + apt)"

FBIPV4

    # --- Performance & Reliability Tuning ---
    cat >> "$output_file" <<'FBPERF'
# --- TCP BBR Congestion Control ---
cat > /etc/sysctl.d/99-tcp-bbr.conf <<'BBR_EOF'
net.core.default_qdisc=fq
net.ipv4.tcp_congestion_control=bbr
BBR_EOF

# --- TCP Fast Open ---
cat > /etc/sysctl.d/99-tcp-fastopen.conf <<'TFO_EOF'
net.ipv4.tcp_fastopen=3
TFO_EOF

# --- Reduce Swappiness (hypervisors should not swap aggressively) ---
cat > /etc/sysctl.d/99-swap.conf <<'SWAP_EOF'
vm.swappiness=10
SWAP_EOF

# --- Kernel Panic Auto-Reboot (critical for unattended servers) ---
cat > /etc/sysctl.d/99-kernel-panic.conf <<'PANIC_EOF'
kernel.panic=10
kernel.panic_on_oops=1
PANIC_EOF

# --- Increase inotify Watches (prevents "no space left" with many containers) ---
cat > /etc/sysctl.d/99-inotify.conf <<'INOT_EOF'
fs.inotify.max_user_watches=1048576
fs.inotify.max_user_instances=1048576
fs.inotify.max_queued_events=1048576
INOT_EOF

# Apply all sysctl tweaks
sysctl --system >/dev/null 2>&1 || true
echo "[$(date)] Performance tuning applied (BBR, fastopen, swappiness, panic, inotify)"

# --- Journald Size Limit (prevent unbounded log growth) ---
mkdir -p /etc/systemd/journald.conf.d
cat > /etc/systemd/journald.conf.d/99-size-limit.conf <<'JOURNAL_EOF'
[Journal]
SystemMaxUse=64M
RuntimeMaxUse=64M
JOURNAL_EOF
systemctl restart systemd-journald 2>/dev/null || true
echo "[$(date)] Journald limited to 64M"

FBPERF

    # ZFS ARC tuning (only for ZFS installs)
    if [[ "$PVE_FILESYSTEM" == "zfs" ]]; then
        # Calculate ARC limits based on total RAM:
        # arc_min = ~5% of RAM (floor for cache, prevents thrashing)
        # arc_max = ~15% of RAM (generous but leaves room for VMs)
        # Uses PVE_ZFS_ARC_MAX from config if explicitly set
        local total_ram_gb=$(( PVE_QEMU_RAM_MB / 1024 * 4 / 3 ))  # approximate host RAM from QEMU alloc
        if [[ -f /proc/meminfo ]]; then
            local total_kb
            total_kb="$(grep MemTotal /proc/meminfo 2>/dev/null | awk '{print $2}')"
            total_ram_gb=$(( total_kb / 1024 / 1024 ))
        fi

        local arc_min_gb=$(( total_ram_gb * 5 / 100 ))
        local arc_max_gb=$(( total_ram_gb * 15 / 100 ))
        # Enforce sane minimums
        if (( arc_min_gb < 1 )); then arc_min_gb=1; fi
        if (( arc_max_gb < 2 )); then arc_max_gb=2; fi
        # Use explicit override if provided
        if [[ -n "$PVE_ZFS_ARC_MAX" ]]; then
            arc_max_gb=$(( PVE_ZFS_ARC_MAX / 1024 ))
        fi

        local arc_min_bytes=$(( arc_min_gb * 1024 * 1024 * 1024 ))
        local arc_max_bytes=$(( arc_max_gb * 1024 * 1024 * 1024 ))

        cat >> "$output_file" <<FBZFS
# --- ZFS ARC Memory Tuning ---
# Host RAM: ~${total_ram_gb} GB -> ARC min: ${arc_min_gb} GB, max: ${arc_max_gb} GB
rm -f /etc/modprobe.d/zfs.conf
cat > /etc/modprobe.d/99-zfs.conf <<'ZFS_EOF'
options zfs zfs_arc_min=${arc_min_bytes}
options zfs zfs_arc_max=${arc_max_bytes}
ZFS_EOF
update-initramfs -u -k all >/dev/null 2>&1 || true
echo "[\$(date)] ZFS ARC tuned: min=${arc_min_gb}GB max=${arc_max_gb}GB"

FBZFS
    fi

    # nf_conntrack module for NAT
    if [[ "$PVE_NETWORK_MODE" == "nat" ]]; then
        cat >> "$output_file" <<'FBCONNTRACK'
# --- Conntrack Module ---
if ! grep -q '^nf_conntrack$' /etc/modules 2>/dev/null; then
    echo "nf_conntrack" >> /etc/modules
fi
modprobe nf_conntrack 2>/dev/null || true
echo "[$(date)] nf_conntrack module configured"

FBCONNTRACK
    fi

    cat >> "$output_file" <<FBAPT
# --- APT Sources ---
# Disable ALL enterprise repos (require paid subscription).
# Proxmox uses various filenames across versions:
#   pve-enterprise.list, ceph.list          (legacy .list format)
#   pve-enterprise.sources, ceph.sources    (DEB822 .sources format)
# Also catch any file containing enterprise.proxmox.com
for f in /etc/apt/sources.list.d/pve-enterprise.list \
         /etc/apt/sources.list.d/pve-enterprise.sources \
         /etc/apt/sources.list.d/ceph.list \
         /etc/apt/sources.list.d/ceph.sources; do
    if [ -f "\$f" ]; then
        mv "\$f" "\${f}.disabled"
        echo "[\$(date)] Disabled enterprise repo: \$f"
    fi
done

# Catch any remaining files that reference enterprise.proxmox.com
for f in /etc/apt/sources.list.d/*.list /etc/apt/sources.list.d/*.sources; do
    if [ -f "\$f" ] && grep -q 'enterprise.proxmox.com' "\$f" 2>/dev/null; then
        mv "\$f" "\${f}.disabled"
        echo "[\$(date)] Disabled enterprise repo: \$f"
    fi
done

# Backup original sources.list if it exists
if [ -f /etc/apt/sources.list ] && [ -s /etc/apt/sources.list ]; then
    mv /etc/apt/sources.list /etc/apt/sources.list.bak
fi

# Add Proxmox no-subscription repos (PVE + Ceph)
cat > /etc/apt/sources.list.d/pve-no-subscription.list <<'PVEREPO_EOF'
deb http://download.proxmox.com/debian/pve ${PVE_DEBIAN_SUITE} pve-no-subscription
PVEREPO_EOF

cat > /etc/apt/sources.list.d/ceph-no-subscription.list <<'CEPHREPO_EOF'
deb http://download.proxmox.com/debian/ceph-squid ${PVE_DEBIAN_SUITE} no-subscription
CEPHREPO_EOF

echo "[\$(date)] APT sources configured (no-subscription repos for PVE + Ceph)"

FBAPT

    cat >> "$output_file" <<'FBSERVICES'
# --- Services ---
systemctl disable --now rpcbind rpcbind.socket 2>/dev/null || true
echo "[$(date)] Unnecessary services disabled"

FBSERVICES

    # --- DHCP Server on vmbr1 (NAT mode only) ---
    if [[ "$PVE_NETWORK_MODE" == "nat" ]] && [[ "$PVE_ENABLE_DHCP" == true ]]; then
        local dhcp_prefix
        dhcp_prefix="$(echo "$PVE_PRIVATE_SUBNET" | cut -d'/' -f1 | rev | cut -d'.' -f2- | rev)"
        local dhcp_start="${dhcp_prefix}.100"
        local dhcp_end="${dhcp_prefix}.200"
        local dhcp_gw="${dhcp_prefix}.1"

        cat >> "$output_file" <<FBDHCP
# --- DHCP Server (dnsmasq) on vmbr1 -- BEST EFFORT ------------------------
# dnsmasq is a convenience: VMs on vmbr1 auto-get IPs. If apt cannot reach
# Debian/Proxmox mirrors right now we MUST NOT abort the entire first-boot
# (the install otherwise succeeded). Retry 3x then move on with a warning.
echo "[\$(date)] Installing dnsmasq for vmbr1 DHCP (best effort)..."
dnsmasq_installed=0
for attempt in 1 2 3; do
    if apt-get update -qq >/dev/null 2>&1 && \\
       DEBIAN_FRONTEND=noninteractive apt-get install -yq dnsmasq >/dev/null 2>&1; then
        dnsmasq_installed=1
        break
    fi
    echo "[\$(date)] dnsmasq install attempt \${attempt} failed, retry in 10s..."
    sleep 10
done

if [ "\$dnsmasq_installed" = 1 ]; then
    # Prevent dnsmasq from interfering with system DNS on port 53
    cat > /etc/dnsmasq.d/00-base.conf <<'DNSMASQ_BASE_EOF'
# Only listen on vmbr1, not on all interfaces
bind-interfaces
except-interface=lo
except-interface=vmbr0
DNSMASQ_BASE_EOF

    cat > /etc/dnsmasq.d/vmbr1-dhcp.conf <<'DNSMASQ_EOF'
# DHCP server for NAT bridge (vmbr1)
interface=vmbr1
dhcp-range=${dhcp_start},${dhcp_end},255.255.255.0,12h
dhcp-option=3,${dhcp_gw}
dhcp-option=6,${PVE_DNS_SERVERS// /,}
DNSMASQ_EOF

    systemctl enable dnsmasq 2>/dev/null || true
    systemctl restart dnsmasq 2>/dev/null || true
    echo "[\$(date)] DHCP server configured on vmbr1 (${dhcp_start}-${dhcp_end})"
else
    echo "[\$(date)] WARN: dnsmasq install failed after 3 attempts."
    echo "[\$(date)]       VMs on vmbr1 will need manual static IP assignment."
    echo "[\$(date)]       To enable DHCP later, run:"
    echo "[\$(date)]         apt-get install -y dnsmasq"
    echo "[\$(date)]         (then re-run pve-dedicated to write the dnsmasq config)"
fi

FBDHCP
    fi

    cat >> "$output_file" <<'FBSUB'
# --- Remove Subscription Nag ---
PROXMOXLIB="/usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js"
if [ -f "$PROXMOXLIB" ]; then
    sed -Ezi.bak \
        "s/(Ext.Msg.show\(\{\s+title: gettext\('No valid sub)/void\(\{ \/\/\1/g" \
        "$PROXMOXLIB"
    systemctl restart pveproxy.service 2>/dev/null || true

    # Create a daily cron so the nag stays removed after apt upgrades
    cat > /etc/cron.daily/pve-nosub <<'CRON_EOF'
#!/bin/sh
PROXMOXLIB="/usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js"
[ -f "$PROXMOXLIB" ] && sed -Ezi \
    "s/(Ext.Msg.show\(\{\s+title: gettext\('No valid sub)/void\(\{ \/\/\1/g" \
    "$PROXMOXLIB"
CRON_EOF
    chmod 755 /etc/cron.daily/pve-nosub

    echo "[$(date)] Subscription notice removed (+ daily cron to persist)"
fi

FBSUB

    # --- SSH Hardening (only if keys were provided) ---
    if [[ -n "$PVE_SSH_KEYS" ]]; then
        # Write keys into the script as a heredoc
        local escaped_keys
        escaped_keys="$(echo "$PVE_SSH_KEYS" | sed 's/\\/\\\\/g')"

        cat >> "$output_file" <<FBSSH
# --- SSH Hardening ---
mkdir -p /root/.ssh
chmod 700 /root/.ssh

cat > /root/.ssh/authorized_keys <<'SSHKEYS_EOF'
${escaped_keys}
SSHKEYS_EOF
chmod 600 /root/.ssh/authorized_keys

# Proxmox cluster-synced authorized_keys (available after pmxcfs starts).
# On installed Proxmox /root/.ssh/authorized_keys is a SYMLINK to
# /etc/pve/priv/authorized_keys (cluster-shared via pmxcfs). The cat above
# already wrote through the symlink, so a plain cp would self-copy and
# return 1 ("are the same file"), which under set -e kills the entire
# first-boot script. Skip the cp when both paths canonicalize to the same
# file; only copy when they're genuinely separate.
if [ -d /etc/pve/priv ]; then
    src_path="\$(readlink -f /root/.ssh/authorized_keys 2>/dev/null || true)"
    dst_path="\$(readlink -f /etc/pve/priv/authorized_keys 2>/dev/null || true)"
    if [ -n "\$src_path" ] && [ "\$src_path" = "\$dst_path" ]; then
        echo "[\$(date)] SSH keys already cluster-synced via symlink (skipping cp)"
    elif cp /root/.ssh/authorized_keys /etc/pve/priv/authorized_keys 2>/dev/null; then
        echo "[\$(date)] SSH keys installed to /etc/pve/priv/authorized_keys (cluster-synced)"
    else
        echo "[\$(date)] WARN: failed to copy SSH keys to /etc/pve/priv (continuing)"
    fi
fi

# Drop-in config -- does not modify the main sshd_config
cat > /etc/ssh/sshd_config.d/99-hardening.conf <<'SSHD_EOF'
# Proxmox-safe SSH hardening (cluster-compatible)
# PermitRootLogin must be prohibit-password, NOT no (breaks clustering)
PermitRootLogin prohibit-password
PasswordAuthentication no
PubkeyAuthentication yes
KbdInteractiveAuthentication no
MaxAuthTries 3
X11Forwarding no
SSHD_EOF

systemctl restart sshd 2>/dev/null || systemctl restart ssh 2>/dev/null || true
echo "[\\$(date)] SSH hardened: password login disabled, key-only access"

FBSSH
    else
        cat >> "$output_file" <<'FBSSH_SKIP'
# --- SSH Hardening SKIPPED ---
# No SSH keys were provided during installation.
# Password login remains enabled. To harden later:
#   1. Add your public key to /root/.ssh/authorized_keys
#   2. Copy to /etc/pve/priv/authorized_keys (for cluster sync)
#   3. Create /etc/ssh/sshd_config.d/99-hardening.conf with:
#        PermitRootLogin prohibit-password
#        PasswordAuthentication no
#   4. systemctl restart sshd
echo "[$(date)] SSH hardening skipped (no keys provided)"

FBSSH_SKIP
    fi

    cat >> "$output_file" <<'FBBACKUP'
# --- Vzdump Backup Speed + Pigz ---
if [ -f /etc/vzdump.conf ]; then
    sed -i "s/#bwlimit:.*/bwlimit: 0/" /etc/vzdump.conf
    sed -i "s/#ionice:.*/ionice: 5/" /etc/vzdump.conf
    sed -i "s/#pigz:.*/pigz: 1/" /etc/vzdump.conf
fi
DEBIAN_FRONTEND=noninteractive apt-get install -yq pigz >/dev/null 2>&1 || true
echo "[$(date)] Backup speed optimized (pigz, no bwlimit)"

FBBACKUP

    cat >> "$output_file" <<'FBDONE'
echo "[$(date)] First-boot configuration complete!"
echo "System is ready. Access web UI at https://$(hostname -I | awk '{print $1}'):8006"
FBDONE

    chmod +x "$output_file"

    if declare -F luks_premium_inject_firstboot >/dev/null; then
        luks_premium_inject_firstboot "$output_file"
    fi

    ui_success "First-boot script generated"
    log_debug "First-boot script: ${output_file}"
}

# Back-compat shim. Prefer provider_render_interfaces; this delegates so
# legacy callers (ssh-config.sh fallback) keep working.
firstboot_render_interfaces() {
    provider_render_interfaces
}

firstboot_render_hosts() {
    cat <<HOSTS
127.0.0.1 localhost.localdomain localhost
${PVE_MAIN_IPV4} ${PVE_FQDN} ${PVE_HOSTNAME}

# IPv6
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
$(if [[ -n "$PVE_IPV6" ]]; then
echo "${PVE_IPV6} ${PVE_FQDN} ${PVE_HOSTNAME}"
fi)
HOSTS
}

# Check if first-boot hooks are supported by checking the ISO version
firstboot_is_supported() {
    if ! command -v proxmox-auto-install-assistant &>/dev/null; then
        return 1
    fi

    if proxmox-auto-install-assistant prepare-iso --help 2>&1 | grep -q 'on-first-boot'; then
        return 0
    fi

    return 1
}
